### ISSUE TITLE
Identifying Multiple Bean

### ISSUE THREAD

**Issue by nirjon** [PunchThrough/Bean-Android-SDK#13]
Is it possible to identify which bean we are talking to when using BeanListener? For example, when we connect to multiple beans and use a single BeanListener - how do we know which Bean just got connected or disconnected etc..?

**Comment by swstack** [comment]
Hi @nirjon 

Unfortunately there is no great way to connect to multiple beans using the same `BeanListener`.  I wrote a quick test that exercises this scenario which you can view in PR14. I think there might be some value in changing the API so that the `Bean` context is passed through to the `BeanListener` callbacks, but I will create a separate ticket for that.
